apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-26ur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-26ur
    app.kubernetes.io/part-of: devfile-sample-4
  name: devfile-sample-26ur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-26ur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-26ur
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-jorringe-tenant/devfile-sample-4/devfile-sample-26ur@sha256:bb6715d949112bfcca950c6099f79c78cd21c069260fe3d70dfe4ad15ce52685
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
